Home task 8
johnlitvinov/RobotDreams pull request #6
Opened 2022-06-02 17:08 UTC by johnlitvinov

2022-06-03 16:06 UTC, taraskarpenko requested changes

2022-06-03 16:06 UTC, taraskarpenko commented on src/main/java/Group.java
> +    public Student changeChief(Student cheifOfGroup){
А что если сюда передать null?

2022-06-03 16:06 UTC, taraskarpenko commented on src/main/java/Group.java
> +        students.put(idInGroup,student);
Получается что один и тот же студент может быть в группе под двумя разными номерами

2022-06-03 16:06 UTC, taraskarpenko commented on src/main/java/Group.java
> +    public boolean removeStudent(int groupId){
Имя переменной groupId выглядит так буд то это идентификатор группы, в то время как на самом деле это идентификатор студента.
Как по мне то лучше вообще отказаться от идентификатора студента в группе, полагаться на собственный идентификатор студента
Если добавить в класс Студент парочку необходимых методов, то можно список сдуентов вообще сделать HashMap

2022-06-06 09:52 UTC, johnlitvinov commented
@taraskarpenko 
Привет, избавился от GroupID и добавил проверки на null, спасибо
https://github.com/johnlitvinov/RobotDreams/pull/6/commits/e12bd09a969abcb00e0e06d7e7dbd84d96c50590

2022-06-13 15:02 UTC, closed without merging